version: "3.7"

networks:
    websita:

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile_nginx.dockerfile
    container_name: webserver
    restart: always
    ports:
      - 8083:80
    networks:
            - websita


  database:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 2171675
      POSTGRES_USER: josequezada
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
            - websita

volumes:
  pgdata:
